// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TodoAPI_Ng.Data;

namespace TodoAPI_Ng.Migrations
{
    [DbContext(typeof(ToDoNgDbContext))]
    [Migration("20180412032437_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TodoAPI_Ng.Models.ToDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDone");

                    b.Property<int?>("ListId");

                    b.Property<string>("Message");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.ToTable("ToDo");
                });

            modelBuilder.Entity("TodoAPI_Ng.Models.ToDoList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ToDoList");
                });

            modelBuilder.Entity("TodoAPI_Ng.Models.ToDo", b =>
                {
                    b.HasOne("TodoAPI_Ng.Models.ToDoList", "List")
                        .WithMany("Items")
                        .HasForeignKey("ListId");
                });
#pragma warning restore 612, 618
        }
    }
}
